Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
s1 = "O=C([O-])C1=CC=CC=C1C(=O)NCC2=CC=CC=C2NCCC"
s2 = "O=C(OC)C1=CC=CC=C1C(=O)NCC2=CC=CC=C2NCCC"
e1 = exmol.Example(s1, "", 0, 0, 0, is_origin=True)
e2 = exmol.Example(s2, "", 0.9, 1.0, 1.0, label="Counterfactual")
fkw = {"figsize": (8, 6)}
font = {"family": "normal", "weight": "normal", "size": 22}

mpl.rc("axes", titlesize=12)
exmol.plot_cf([e1, e2], figure_kwargs=fkw, mol_size=(450, 400), nrows=1)
plt.tight_layout()
svg = exmol.insert_svg([e1, e2])
with open("counterfactual.svg", "w") as f:
    f.write(svg)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mUnboundLocalError[0m                         Traceback (most recent call last)
Cell [0;32mIn [2], line 9[0m
[1;32m      6[0m font [38;5;241m=[39m {[38;5;124m"[39m[38;5;124mfamily[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124mnormal[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mweight[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124mnormal[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124msize[39m[38;5;124m"[39m: [38;5;241m22[39m}
[1;32m      8[0m mpl[38;5;241m.[39mrc([38;5;124m"[39m[38;5;124maxes[39m[38;5;124m"[39m, titlesize[38;5;241m=[39m[38;5;241m12[39m)
[0;32m----> 9[0m [43mexmol[49m[38;5;241;43m.[39;49m[43mplot_cf[49m[43m([49m[43m[[49m[43me1[49m[43m,[49m[43m [49m[43me2[49m[43m][49m[43m,[49m[43m [49m[43mfigure_kwargs[49m[38;5;241;43m=[39;49m[43mfkw[49m[43m,[49m[43m [49m[43mmol_size[49m[38;5;241;43m=[39;49m[43m([49m[38;5;241;43m450[39;49m[43m,[49m[43m [49m[38;5;241;43m400[39;49m[43m)[49m[43m,[49m[43m [49m[43mnrows[49m[38;5;241;43m=[39;49m[38;5;241;43m1[39;49m[43m)[49m
[1;32m     10[0m plt[38;5;241m.[39mtight_layout()
[1;32m     11[0m svg [38;5;241m=[39m exmol[38;5;241m.[39minsert_svg([e1, e2])

File [0;32m/opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/exmol/exmol.py:980[0m, in [0;36mplot_cf[0;34m(exps, fig, figure_kwargs, mol_size, mol_fontsize, nrows, ncols)[0m
[1;32m    978[0m [38;5;28;01melse[39;00m:
[1;32m    979[0m     axs [38;5;241m=[39m fig[38;5;241m.[39msubplots(R, C)
[0;32m--> 980[0m [38;5;28;01mif[39;00m [38;5;28mtype[39m([43maxes[49m) [38;5;241m!=[39m np[38;5;241m.[39mndarray:  [38;5;66;03m# Happens if nrows=ncols=1[39;00m
[1;32m    981[0m     axes [38;5;241m=[39m np[38;5;241m.[39marray([[axes]])
[1;32m    982[0m axs [38;5;241m=[39m axs[38;5;241m.[39mflatten()

[0;31mUnboundLocalError[0m: local variable 'axes' referenced before assignment
UnboundLocalError: local variable 'axes' referenced before assignment

